fixtures:
  repositories:
    stdlib: 'https://github.com/puppetlabs/puppetlabs-stdlib'
    vcsrepo: 'https://github.com/puppetlabs/puppetlabs-vcsrepo'
    redis: 'https://github.com/arioch/puppet-redis'
